### ISSUE TITLE
instance.subscribe match $SYS topic

### ISSUE THREAD

**Issue by nuhamind2** [moscajs/aedes#221]
instance.subscribe with '#' topic match $SYS
related #135 

Even without connected client, it will match it's own heartbeat

Test code:

```
var aedes = require('aedes')()
var httpServer = require('http').createServer()
var websocket = require('websocket-stream')

httpServer.listen(9090, 'localhost', function () {
    console.log("Server listening")
})

ws = websocket.createServer({
    server: httpServer, verifyClient: function (info) {
        return true
    }
}, aedes.handle)

aedes.subscribe("#",function(packet, done){
    console.log(`this catch all sub receive ${packet.topic} and ${packet.payload.toString()}`)
    done()
},function(){})```

**Comment by gnought** [comment]
good catch.

**Comment by robertsLando** [comment]
@mcollina Has this been fixed?

**Comment by mcollina** [comment]
no clue

Il giorno gio 23 gen 2020 alle ore 12:26 Daniel Lando <
notifications@github.com> ha scritto:

**Comment by robertsLando** [comment]
@gnought Do you know ?

**Comment by Debdutto** [comment]
Hi @robertsLando

I could still reproduce this with the test script provided with the latest version `0.40.1`
`#` still matches `$SYS` topics and receives its own heartbeats.

**Comment by robertsLando** [comment]
@Debdutto Thanks!

**Comment by robertsLando** [comment]
It should be fixed by https://github.com/moscajs/aedes/pull/312 @gnought ?

**Comment by gnought** [comment]
@robertsLando yes, it should be fixed.
@Debdutto what's your test script. Here is mine:
```
test.only('does not forward $SYS prefixed topics to # subscription', function (t) {
  t.plan(4)

  var s = connect(setup())

  subscribe(t, s, '#', 0, function () {
    s.outStream.once('data', function (packet) {
      t.fail('no packet should be received')
    })

    s.broker.mq.emit({
      cmd: 'publish',
      topic: '$SYS/hello',
      payload: 'world'
    }, function () {
      t.pass('nothing happened')
    })
  })
})
```

**Comment by Debdutto** [comment]
Hi @gnought @robertsLando The script I used (which is based of the test script in the issue) still reproduces the issue with `aedes@0.40.1`

Here's the script:

```
var aedes = require('aedes')()
var httpServer = require('http').createServer()

httpServer.listen(9090, 'localhost', function () {
    console.log("Server listening")
})

aedes.subscribe("#",function(packet, done){
    console.log(new Date()) 
    console.log(`Topic: ${packet.topic}, Payload: ${packet.payload.toString()}`)
    console.log('--') 
    done()
},function(){})
```

Here are the logs 


```
Server listening
2020-02-24T10:02:16.168Z
Topic: $SYS/484de899-6f75-43c4-bfc3-c6624dcb2443/heartbeat, Payload: 484de899-6f75-43c4-bfc3-c6624dcb2443

2020-02-24T10:03:16.176Z
Topic: $SYS/484de899-6f75-43c4-bfc3-c6624dcb2443/heartbeat, Payload: 484de899-6f75-43c4-bfc3-c6624dcb2443

2020-02-24T10:04:16.177Z
Topic: $SYS/484de899-6f75-43c4-bfc3-c6624dcb2443/heartbeat, Payload: 484de899-6f75-43c4-bfc3-c6624dcb2443
```

**Comment by robertsLando** [comment]
@Debdutto That's correct because the check is only done on clients, broker can subscribe to everything

**Comment by Debdutto** [comment]
Right. Got it. Thanks. 👍
