### ISSUE TITLE
Protocol decoder not always working with TCP proxy

### ISSUE THREAD

**Issue by getlarge** [moscajs/aedes#364]
There is still an issue in the the protocol decoder when Aedes broker is used behind a TCP proxy which handles SSL termination.
The packet is splitted in two, on one side the protocol proxy header and the TCP buffer on the other.
Any help to solve this would be appreciated.

_Originally posted by @getlarge in https://github.com/moscajs/aedes/issues/338#issuecomment-577841457_

**Comment by robertsLando** [comment]
@mcollina Any suggestion for this?

**Comment by mcollina** [comment]
I think this was solved in https://github.com/moscajs/aedes/pull/334.

**Comment by robertsLando** [comment]
@mcollina @getlarge Is the author of that PR so I think this is not fixed

**Comment by robertsLando** [comment]
@getlarge Could you create an example to reproduce this bug?

**Comment by getlarge** [comment]
Sure, but it's not so simple to reproduce.
It would require to start an app with Aedes + MQTT client and have Nginx or HAProxy running with some SSL certs.
Should i provide a docker-compose file for this ?

**Comment by robertsLando** [comment]
I think a docker compose would be fine :)

**Comment by getlarge** [comment]
Now i'm confused, i created a [test repo](https://github.com/getlarge/aedes-proxy)  for this case and it seems to work well.
So the issue might be specific to a Nginx configuration point and / or maybe docker-compose networks since i saw this issue in this context.
I will try to figure how to reproduce it.

**Comment by robertsLando** [comment]
@getlarge Let me know

**Comment by getlarge** [comment]
@robertsLando So after some more tests, it seems the bug appears "randomly" ( because i don't understand why), that's why i didn't catch it yesterday.
As you can see on the screenshot, sometimes the new connection triggers protocolDecoder once, and some other time it triggers it twice.
It might happen due to the condition in nextBatch ?  Because nextBatch would be triggered twice before connack is sent ?

![error_screenshot](https://user-images.githubusercontent.com/15331923/73348303-7343d700-4289-11ea-957e-1eca64cae28d.png)

**Comment by robertsLando** [comment]
@getlarge In latest commit nextBatch call in client init has been removed. Coould you use the version from master to test this?

**Comment by getlarge** [comment]
I already use the github repo in `package.json`, and when the image is built all dependencies are installed.
I will try to confirm.

**Comment by robertsLando** [comment]
So you are not using npm install aedes (that installs latest npm version 0.40.1) but are you cloning it from github?

With npm install moscajs/aedes/#master you use latest code available on master instead latest published version

**Comment by getlarge** [comment]
Yes i cloned it from github to have the decodeProtocol hook.

**Comment by robertsLando** [comment]
The fix has landed yesterday so if you are sure you are running it from the master now that is not the problem. Let's wait if @mcollina has any other suggestion

**Comment by getlarge** [comment]
In fact i'm going to rename the issue, since the problem occurs ( it seems less often ) when using  a simple TCP connection ( with no SSL ).

**Comment by getlarge** [comment]
The only trick i found to avoid this issue, is to remove the else condition when no data has been extracted from the `broker.decodeProtocol`.
So in this case the client sends the connection packet several times ( in fact 2 times, it seems to be constant ) and the connack is only sent when the buffer is composed of the proxy header and the mqtt packet.
Not sure this is the right way to handle this bug, because the drawback is that if you assign broker.trustProxy = true, your client must always be behind a proxy ( or inject proxy header itself ) to handle connection.
Any suggestion ?

**Comment by robertsLando** [comment]
@getlarge When protocol decoder fails, what is the buffer received?

**Comment by getlarge** [comment]
`var {data}` that's the TCP Buffer (containing only the MQTT packet) extracted without the proxy protocol header and it should be present when a client connects behind a TCP proxy.
What is causing the issue is that `data` is empty because only the proxy protocol header was received from `buf` ( even if i don't know why, maybe the size of the client.conn.read buffer ? Or Nginx proxy splitting the buffer ). 

In fact after some thoughts and tests, this seems fine to fix the issue
`var { data, isProxy } = client.broker.decodeProtocol(client, buf)
if (data) {
  client._parser.parse(data)
} else if (!isProxy) {
  client._parser.parse(buf)
}` 

And i would like to suggest to change the condition above this block to 
` if (!client.connackSent && buf) `
Like this even clients which are not behind a proxy would also get their connection information in client.connDetails.

Related to this, i'm currently trying to get a reliable source for the proxy server IP to achieve this #338
Then i will send a PR.

**Comment by robertsLando** [comment]
@gnought Thoughts on this?

**Comment by robertsLando** [comment]
> Like this even clients which are not behind a proxy would also get their connection information in client.connDetails.

Shouldn't also clients connected using websockets get them?

**Comment by getlarge** [comment]
@robertsLando Yes clients using websockets would, ( from socket._socket ) and if broker.trustProxy = true, they would get in priority information from headers set by the proxy server.

**Comment by robertsLando** [comment]
> What is causing the issue is that data is empty because only the proxy protocol header was received from buf ( even if i don't know why, maybe the size of the client.conn.read buffer ? Or Nginx proxy splitting the buffer ).

Could it be a protocol or nginx related behaviour to firstly send a packet with empty data field? Should check specs about them to check if this is normal

About `if (!client.connackSent && buf)`, I upvote this so like you said even clients which are not behind a proxy would also get their connection information in `client.connDetails`

But maybe this could slow down a little packets parsing when not using a proxy?

**Comment by getlarge** [comment]
It could be related to the specs, but then why this issue would appear randomly ?
"Sometimes" the MQTT packet and the Proxy header are concatenated in the same buffer and "sometimes" they are separated.
I can't see any clarification in [Proxy Protocol spec](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) neither in [Nginx Docs](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).

I tried to reproduce the NGINX proxy behaviour with 2 TCP servers to write a test ( one for the Aedes and one acting as a Proxy ) but the issue never seems to happen.
So yes it might comes from NGINX...

**Comment by getlarge** [comment]
@robertsLando following the change with protocolDecoder, you forgot to implement the condition changes that fixes this issue.
Unless it was on purpose ?
Also we suggested that client.broker.trustProxy should not need be true to go through broker.protocolDecoder. Should i make a PR for this ?

**Comment by robertsLando** [comment]
Yes go for it! 

Daniel

**Comment by robertsLando** [comment]
@getlarge Any news?

**Comment by getlarge** [comment]
@robertsLando  I saw the discussion on #365 and thought it might be smarter to wait until it goes into aedes to bring the change.

**Comment by robertsLando** [comment]
If you want to join that discussion you are welcome, gnought made some changes in his “next” branch that requires some thoughts about protocol decoder. 

Daniel

**Comment by robertsLando** [comment]
@getlarge Could we close this now?

**Comment by getlarge** [comment]
yes
